name: Sonar Code Quality & Security

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  sonar:
    name: Sonar Scan & Quality Gate
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.projectName=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.

      # 3. SonarQube Quality Gate
      #    FAIL -> workflow stops
      #    PASS -> next step runs
      - name: Sonar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 4. Runs ONLY if Quality Gate passes
      - name: Final Test
        run: |
          echo "========================================"
          echo "        SONAR TEST PASSED"
          echo "========================================"
          echo "Quality Gate  : PASSED"
          echo "Security Scan : PASSED"
          echo "Code Analysis : PASSED"
          echo "========================================"
